---
title: 'Exercise 3_2_2: Plotting Repeats'
author: 'Dennis Abel & Jan Schwalbach'
date: 'Introduction to R for Data Analysis'
---

```{r child = "./content/config/exercises_setup.Rmd"}
```

~~History~~ Plotting repeats. Let's dive into `ggplot2` and repeat what we've done in `base R` using the "grammar of graphics".

Here's the Allbus 2021 data again.

```{r loadallbus2021, message=FALSE, eval=TRUE}
library(dplyr)
library(haven)

allbus_2021_dvI <- 
  read_sav(
    "./data/allbus_2021/ZA5280_v2-0-1.sav"
  ) %>% 
  sjlabelled::set_na(na = c(-1:-99, 97, 98))
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Create a scatter plot for the variables `pa01` (political_orientation) and `fr03b` (children suffer under working mothers).
```

```{block, opts.label = "clues"}
Remember the order of layers: `data + aesthetics + geoms`
```

```{r scatter, solution = TRUE}
library(ggplot2)

ggplot(
  allbus_2021_dvI,
  aes(pa01, fr03b)
) +
  geom_point()
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Add some jitter to the scatter plot.
```

```{block, opts.label = "clues"}
In contrast to the `base R` function jitter does not have to be added; it just replaces the original `geom` using `geom_jitter()`
```

```{r jitter, solution = TRUE}
ggplot(
  allbus_2021_dvI,
  aes(pa01, fr03b)
) +
  geom_jitter()
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Let's try out a boxplot. We want to understand the distribution of political orientation for each category of `fr03b`. For this, we treat `fr03b` as factor (see clues) and put it on the x-axis of our boxplot. The boxplot is a distinct geom and is called `geom_boxplot`. You can check out all possible geoms here: https://ggplot2.tidyverse.org/reference/#geoms
```

```{block, opts.label = "clues"}
You already learned how to transform variables from for example numerical to factor in your dataset. If you do not want to transform it permanently but only for this particular visualization, you can just wrap the variable in the command `as.factor`. You `aes`-function will look like this: `aes(x=as.factor(), y=)`.
```

```{r violin, solution = TRUE}
ggplot(allbus_2021_dvI, aes(as.factor(fr03b), pa01)) +
  geom_boxplot()
```
